### ISSUE TITLE
fix "unable to redeem with nft" issue

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-frontend#186]
- [x] in case of 400; print error msg somewhere

- this should be something more like, "not enough erg"
- getting 400s
- solved by consolidating utxos

We need to explain better where the issue exists to the user.
i.e. "unable to redeem due to 'not enough ergo', please do XYZ..."
 ... or "error on ergopad site"

- Alexis suggests a lookup page for errors

**Comment by vikingphoenix** [comment]
This issue will ideally be fixed in the appKit.  Benjamin is making some progress, and this is an edge case that is annoying to fix (shouldn't be the burden of the Dev to fix)

**Comment by esot321c** [comment]
Follow up with Theta and Alexis to log reports of this issue

**Comment by Luivatra** [comment]
The suspicion I had was not correct, can't see in the code what could be an issue. We need some more detailed error logs before we spend more time on it (how often is it still happening?)

**Comment by vikingphoenix** [comment]
reword, "unable to redeem in this moment, please try again shortly. If prob continues, contact team on tg or..."
