### ISSUE TITLE
move from lightsail to vercel

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-frontend#202]
- move ergopad and paideia to containers on delta
- setup single nginx repo that git pulls both sites
- optionally, setup load balancing and add frontend container to alpha

**Comment by esot321c** [comment]
Encountered an issue with our API interaction where we're using nginx reverse proxy that did not translate to Vercel. Will continue to follow up (Leif and Marty)

**Comment by vikingphoenix** [comment]
- api.domain.com will point to alpha
- app config will point all API URLs there; without the need for nginx
- proposing change to https://api.ergopad.io/ so we don't need nginx to reroute anything
