### ISSUE TITLE
purchase page for paideia staker round

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-frontend#92]
- [x] enable dapp connector
- [x] update text/details

**Comment by Luivatra** [comment]
Each round will have a unique identifier (tokenid of the NFT belonging to that round)

The following endpoints will be available:
/vesting/requiredNergTokens
request:

- proxyNFT: str
- vestingAmount: Decimal
- sigUSDAmount: Decimal

Response:

- nErgRequired: int
- tokens: []
  - tokenId: str
  - amount: int
  
 This can be used to fetch boxes with get_utxos.
 
/vesting/vestFromProxy
Request

- proxyNFT: str
- vestingAmount: Decimal
- sigUSDAmount: Decimal
- address: str
- utxos: list[str]

Response

- unsignedTransaction

The address is for the change box, it is not guaranteed this is where the vesting key ends up. The endpoints can handle the user buying partly with sigusd (say they need to pay 100 sigusd, they can pay 50 sigusd + 50 sigusd worth of erg).
